name: CI Front
on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch: {}

jobs:
  front-sb-test-performance:
    runs-on: ubuntu-22.04
    name: sb-test-perf-depot
    # timeout-minutes: 60
    env:
      REACT_APP_SERVER_BASE_URL: http://localhost:3000
      NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
    steps:
      - name: Fetch local actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/workflows/actions/yarn-install
      - name: Install Playwright
        run: cd packages/twenty-front && npx playwright install
      - name: Front / Write .env
        run: npx nx reset:env twenty-front
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
      - name: Run storybook tests
        run: npx nx run twenty-front:storybook:serve-and-test:static:performance
        
